/**
 * @file bemf_zc.h
 * @brief Digital BEMF zero-crossing detection using ATA6847 comparators.
 *
 * The ATA6847 has built-in BEMF comparators (GDUCR1.BEMFEN=1) that
 * output digital signals on GPIO pins:
 *   RC6 = Phase A BEMF comparator
 *   RC7 = Phase B BEMF comparator
 *   RD10 = Phase C BEMF comparator
 *
 * These outputs go high when the floating phase voltage crosses the
 * virtual neutral point (internally generated by ATA6847).
 *
 * Detection paths:
 *   FEATURE_IC_ZC=1: SCCP1 100kHz fast poll (primary) + ADC ISR backup
 *   FEATURE_IC_ZC=0: ADC ISR 20kHz polling only
 */

#ifndef BEMF_ZC_H
#define BEMF_ZC_H

#include <stdint.h>
#include <stdbool.h>
#include "../garuda_types.h"

void BEMF_ZC_Init(volatile GARUDA_DATA_T *pData);
void BEMF_ZC_OnCommutation(volatile GARUDA_DATA_T *pData);
bool BEMF_ZC_Poll(volatile GARUDA_DATA_T *pData);
ZC_TIMEOUT_RESULT_T BEMF_ZC_CheckTimeout(volatile GARUDA_DATA_T *pData);
void BEMF_ZC_ScheduleCommutation(volatile GARUDA_DATA_T *pData);

#if FEATURE_IC_ZC
/**
 * @brief Fast poll ZC detection — called from SCCP1 timer ISR at 200kHz.
 * Reads the floating phase comparator and applies adaptive deglitch filter.
 * Uses SCCP4 timestamps for 640ns-resolution blanking.
 * @param pData ESC runtime data
 * @return true when ZC is confirmed (caller should schedule commutation)
 */
bool BEMF_ZC_FastPoll(volatile GARUDA_DATA_T *pData);

/**
 * @brief Record ZC timing and update step period estimator.
 * Non-static: called from both FastPoll and _CCP2Interrupt (IC path).
 */
void RecordZcTiming(volatile GARUDA_DATA_T *pData,
                    uint16_t zcTick, uint16_t hrTick);
#endif

#endif /* BEMF_ZC_H */
